package com.github.pannowak.repoapi.repository;

import com.github.pannowak.repoapi.exception.EmployeePersistenceException;
import com.github.pannowak.repoapi.model.Employee;

public abstract class EmployeeRepositoryTemplate implements EmployeeRepository {

    @Override
    public Employee insert(Employee employee) throws EmployeePersistenceException {
        employee.setId(null);
        return insertWithAutoGeneratedKey(employee);
    }

    @Override
    public void update(Employee employee) throws EmployeePersistenceException {
        findById(employee.getId()).orElseThrow(() ->
                new EmployeePersistenceException("Could not update not existing employee"));
        updateExisting(employee);
    }

    protected abstract Employee insertWithAutoGeneratedKey(Employee employee) throws EmployeePersistenceException;

    protected abstract void updateExisting(Employee employee) throws EmployeePersistenceException;
}
